export const DAILY_FREE_LIMITS = {
  SWIPES: 5,
  MESSAGES: 10,
  SWAP_REQUESTS: 2,
  FOLLOWS: 5,
};

export const ACTION_CREDIT_COSTS = {
  EXTRA_SWIPE: 1,
  EXTRA_MESSAGE: 1,
  EXTRA_SWAP_REQUEST: 3,
  EXTRA_FOLLOW: 1,
};
